[project]
name = "llm_metrics"
version = "0.4.0"
description = "Default template for PDM package"
authors = [
    {name = "tkietreiber", email = "tobias.kietreiber@fhstp.ac.at"},
    {name = "tobiasdam", email = "198982749+Copilot@users.noreply.github.com"},
]
dependencies = [
    "langgraph",
    "requests",
    "python-dateutil>=2.9.0.post0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[[tool.pdm.source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"


[tool.pdm.dev-dependencies]
dev = [
    "-e file:///${PROJECT_ROOT}/#egg=llm-metrics",
]
